security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: database_users

            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: blog_index

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                #always_remember_me: true

            logout:
                target: blog_index
                enable_csrf: true

            entry_point: form_login

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/messagerie, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

        firewalls:
            main:
                http_basic: ~

        access_control:
            - { path: ^/messagerie, roles: IS_AUTHENTICATED_FULLY }
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/login, roles: PUBLIC_ACCESS }
            - { path: ^/register, roles: PUBLIC_ACCESS }
