# config/packages/translation.yaml
framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
        providers:
            # Tu peux activer l’un de ces services si tu veux synchroniser tes traductions
            # crowdin:
            #     dsn: '%env(CROWDIN_DSN)%'
            # loco:
            #     dsn: '%env(LOCO_DSN)%'
            # lokalise:
            #     dsn: '%env(LOKALISE_DSN)%'
            # phrase:
            #     dsn: '%env(PHRASE_DSN)%'
