# Page d’accueil rendue par un contrôleur dynamique (recommandé)
homepage:
    path: /
    controller: App\Controller\HomeController::index

# Chargement automatique des contrôleurs avec attributs
controllers:
    resource: '../src/Controller/'
    namespace: App\Controller
    type: attribute
    # Si tu veux des URLs multilingues comme /fr/blog, décommente la ligne ci-dessous
    # prefix: /{_locale}
    defaults:
        _locale: '%app.locale%'
